32bit: USBGuard.c Tools/EnumRegistry.c Tools/Privilages.c Tools/ErrorHandling.c DeviceManagement.c USBGuard.h
	i686-w64-mingw32-gcc -o USBGuard.exe USBGuard.c Tools/EnumRegistry.c Tools/Privilages.c Tools/ErrorHandling.c DeviceManagement.c USBGuard.h

64bit: USBGuard.c Tools/EnumRegistry.c Tools/Privilages.c Tools/ErrorHandling.c DeviceManagement.c USBGuard.h
	x86_64-w64-mingw32-gcc -o USBGuard.exe USBGuard.c Tools/EnumRegistry.c Tools/Privilages.c Tools/ErrorHandling.c DeviceManagement.c USBGuard.h