32bit: USBGuard.c EnumRegistry.c EnumDevices.c USBGuard.h
	i686-w64-mingw32-gcc -o USBGuard.exe USBGuard.c EnumRegistry.c EnumDevices.c USBGuard.h

64bit: USBGuard.c EnumRegistry.c EnumDevices.c USBGuard.h
	x86_64-w64-mingw32-gcc -o USBGuard.exe USBGuard.c EnumRegistry.c EnumDevices.c USBGuard.h